### ISSUE TITLE
questions in advance

### ISSUE THREAD

**Issue by annlarson** [debtcollective/defense-to-repayment-wizard#6]
We met with some students in Detroit last week and got some feedback on the DTR that I thought I’d pass along. They say it would help to be able to see the questions that are going to be asked upfront, so they could prepare their responses. Is there a way to provide a PDF doc or something that just lists the questions so folks can know what to expect and prepare their materials in advance? Obviously this is not super urgent, but I thought it was a good suggestion. Thanks.

**Comment by karissa** [comment]
This repo has been deprecated
